# Site settings
title: David M Richardson
description: "There's not a lot here."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidrichardson.github.io" # the base hostname & protocol for your site
twitter_username: richardson_dm
github_username:  davidrichardson

#jekyll_get:
#  data: publications
#  json: http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=AUTHORID:0000-0003-0247-9118%20sort_date:y&format=json

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
