# Site settings
title: David M Richardson
description: "The personal site of David Richardson."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidrichardson.github.io" # the base hostname & protocol for your site
twitter_username: richardson_dm
github_username:  davidrichardson

#jekyll_get:
#  data: publications
#  json: http://www.ebi.ac.uk/europepmc/webservices/rest/search/resulttype=core&query=AUTHORID:0000-0003-0247-9118%20sort_date:y&format=json
# cd _data ; curl 'http://www.ebi.ac.uk/europepmc/webservices/rest/search/resulttype=core&query=AUTHORID:0000-0003-0247-9118%20sort_date:y&format=json' > publications.json

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
